"""
blog/admin.py

Registers our models with Django's Admin panel.
The admin panel is available at /admin/ — it's a full CRUD interface
automatically generated by Django.

By customizing ModelAdmin classes, we control:
- Which columns appear in the list view
- Which fields are searchable/filterable
- How the edit form looks
"""

from django.contrib import admin
from django.utils.html import format_html
from .models import Post, Category, Comment, UserProfile


# ─────────────────────────────────────────────
# CATEGORY ADMIN
# ─────────────────────────────────────────────
@admin.register(Category)  # Decorator to register model with this admin class
class CategoryAdmin(admin.ModelAdmin):
    """Admin interface for blog categories."""

    # list_display: Columns shown in the admin list view
    list_display = ['name', 'slug', 'color_preview', 'post_count']

    # prepopulated_fields: Auto-fill slug from name as user types
    prepopulated_fields = {'slug': ('name',)}

    # search_fields: Fields searched when using the search box
    search_fields = ['name']

    def color_preview(self, obj):
        """
        Shows a colored square in the admin list.
        format_html safely inserts HTML (prevents XSS injection).
        """
        return format_html(
            '<span style="background-color: {}; padding: 3px 12px; '
            'border-radius: 4px; color: white;">{}</span>',
            obj.color,
            obj.color
        )
    color_preview.short_description = 'Color'

    def post_count(self, obj):
        """Shows how many published posts this category has."""
        return obj.posts.filter(status='published').count()
    post_count.short_description = 'Published Posts'


# ─────────────────────────────────────────────
# POST ADMIN
# ─────────────────────────────────────────────
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    """Admin interface for blog posts."""

    list_display = ['title', 'author', 'category', 'status', 'featured',
                    'views', 'created_at', 'thumbnail_preview']
    list_filter = ['status', 'featured', 'category', 'created_at']  # Sidebar filters
    search_fields = ['title', 'excerpt', 'content']
    prepopulated_fields = {'slug': ('title',)}
    raw_id_fields = ['author']   # Shows author search box instead of dropdown

    # readonly_fields: These fields are shown but cannot be edited in admin
    readonly_fields = ['views', 'created_at', 'updated_at', 'thumbnail_preview']

    # fieldsets: Group fields into sections in the edit form
    fieldsets = (
        ('Basic Info', {
            'fields': ('title', 'slug', 'author', 'status', 'featured')
        }),
        ('Content', {
            'fields': ('excerpt', 'content', 'thumbnail', 'thumbnail_preview')
        }),
        ('Organization', {
            'fields': ('category', 'tags')
        }),
        ('Metadata', {
            'fields': ('views', 'created_at', 'updated_at', 'published_at'),
            'classes': ('collapse',),  # Collapsed by default
        }),
    )

    def thumbnail_preview(self, obj):
        """Shows a small thumbnail image in the admin."""
        if obj.thumbnail:
            return format_html(
                '<img src="{}" style="height: 50px; width: auto; border-radius: 4px;">',
                obj.thumbnail.url
            )
        return 'No thumbnail'
    thumbnail_preview.short_description = 'Preview'

    # list_editable: Edit these fields directly in the list view
    list_editable = ['status', 'featured']


# ─────────────────────────────────────────────
# COMMENT ADMIN
# ─────────────────────────────────────────────
@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    """Admin interface for comments — useful for moderation."""

    list_display = ['author', 'post', 'is_approved', 'created_at', 'short_body']
    list_filter = ['is_approved', 'created_at']
    search_fields = ['body', 'author__username', 'post__title']
    list_editable = ['is_approved']  # Approve/reject directly in list view
    actions = ['approve_comments', 'reject_comments']

    def short_body(self, obj):
        """Truncate long comment text for the list view."""
        return obj.body[:80] + '...' if len(obj.body) > 80 else obj.body
    short_body.short_description = 'Comment'

    def approve_comments(self, request, queryset):
        """Bulk approve selected comments."""
        queryset.update(is_approved=True)
        self.message_user(request, f'{queryset.count()} comments approved.')
    approve_comments.short_description = 'Approve selected comments'

    def reject_comments(self, request, queryset):
        """Bulk reject selected comments."""
        queryset.update(is_approved=False)
        self.message_user(request, f'{queryset.count()} comments rejected.')
    reject_comments.short_description = 'Reject selected comments'


# ─────────────────────────────────────────────
# USER PROFILE ADMIN
# ─────────────────────────────────────────────
@admin.register(UserProfile)
class UserProfileAdmin(admin.ModelAdmin):
    """Admin interface for user profiles."""

    list_display = ['user', 'website', 'twitter', 'linkedin']
    search_fields = ['user__username', 'bio']
    raw_id_fields = ['user']


# ─────────────────────────────────────────────
# CUSTOMIZE ADMIN HEADER
# ─────────────────────────────────────────────
admin.site.site_header = "BlogCMS Admin"
admin.site.site_title = "BlogCMS Administration"
admin.site.index_title = "Welcome to BlogCMS Dashboard"
